@startuml
left to right direction
skinparam packageStyle rectangle
actor :player:
rectangle "Simulation of Entertainment Park" {
  :player: -- (work with the visitor)
  (work with the visitor) ..> (move the visitor to the attraction) : <<include>>
  (work with the visitor) <.. (delete visitor) : <<extends>>
  (work with the visitor) <.. (remove a visitor from the park) : <<extends>>
  (work with the visitor) .> (create visitor) : <<include>>
  (create visitor) .> (set visitors salary) : <<include>>

  :player: -- (work with attractions)
  (work with attractions) <.. (remove the attraction) : <<extends>>
  (work with attractions) ..> (buy an attraction) : <<include>>
  (buy an attraction) ..> (no seats available) : <<extends>>
  (buy an attraction) ..> (incorrect sum) : <<extends>>
  (buy an attraction) .> (title assignment) : <<include>>

}
@enduml