@startuml
left to right direction
skinparam packageStyle rectangle
actor :игрок:
rectangle "Симуляция парка развлечений" {
  :игрок: -- (работа с посетителем)
  (работа с посетителем) ..> (определение посетителя на аттракцион) : <<include>>
  (работа с посетителем) <.. (удаление посетителя) : <<extends>>
  (работа с посетителем) <.. (удаление посетителя из парка) : <<extends>>
  (работа с посетителем) .> (создание посетителя) : <<include>>
  (создание посетителя) .> (задание количества средств) : <<include>>

  :игрок: -- (работа с аттракционами)
  (работа с аттракционами) <.. (удаление аттракциона) : <<extends>>
  (работа с аттракционами) ..> (покупка аттракциона) : <<include>>
  (покупка аттракциона) ..> (нет свободных мест) : <<extends>>
  (покупка аттракциона) ..> (некорректная сумма) : <<extends>>
  (покупка аттракциона) .> (задание названия) : <<include>>

}
@enduml
