@startuml add-visitor-to-attraction-activity-diagram
skinparam ConditionEndStyle hline
|Player|
start
:Identify the visitor to the attraction;
|Simulation of Entertainment Park|
fork
:List of visitors on the "Main Valley"]
forkagain
:List of attractions]
endfork
|Player|
fork
:Choose visitors;
forkagain
:Choose an attraction;
endfork
:Confirm action;
|Simulation of Entertainment Park|
:Add selected visitors to the queue for the attraction;
:Remove visitors from "Main Valley";
|Player|
stop
@enduml