@startuml
|Player|
start
:Add a visitor;
|Simulation of Entertainment Park|
:Generate ID;
:ID]
|Player|
repeat
:Enter amount of money;
:Confirm action;
|Simulation of Entertainment Park|
repeat while (Entered number equals from 1 to 100) is (no) not (yes)
:Save changes;
:List of people in the queue]
|Player|
:View changes;
stop
@enduml