@startuml buy-ticket
skinparam ConditionEndStyle hline
|Player|
start
:Buy a ticket;
:Confirm action;
|Simulation of Entertainment Park|
:Calculate ticket price;
:Ticket price]
|Player|
:Choose a visitor;
:Confirm action;
|Simulation of Entertainment Park|
If (visitor has enough money to buy?) then (yes)
:Write down the remaining funds of the visitor;
:Recharge the budget of the park;
:Visitor has been moved to the "Main Valley"]
else (no)
|Simulation of Entertainment Park|
:Remove the visitor from the list;
endif
|Player|
stop
@enduml