@startuml
skinparam ConditionEndStyle hline
|Player|
start
:Buying an attraction;
|Simulation of Entertainment Park|
if (On the "Main Alley" have visitors?) then (no)
If (there are visitors on the ride?) then (no)
:Calculate the cost of the attraction;
:Cost of attraction] 
|Player|
:Confirm action;
|Simulation of Entertainment Park|
if (is there enough money in the park's budget?) then (yes)
:Update park budget value;
|Player|
repeat
:Enter title;
:Confirm action;
|Simulation of Entertainment Park|
repeat while (Is the data correct?) is (no) not (yes)
:Title of attraction]
:Add the attraction to the list;
else (no)
:No action possible]
endif
else (yes)
:No action possible]
endif
else (yes)
:No action possible]
|Player|
endif
stop
@enduml