@startuml view-valley-activity-diagram
skinparam ConditionEndStyle hline
|Player|
start
:Removal of the attraction;
|Simulation of Entertainment Park|
if (are there visitors on the "Main Valley"?) then (no)
If (are there visitors on the attraction?) then (no) 
:List of attractions]
|Player|
:Choose an attraction;
:Confirm action;
|Simulation of Entertainment Park|
:Remove the attraction from the list;
else (yes)
:No action possible]
endif
else (yes)
:No action possible]
|Player|
endif
stop
@enduml