@startuml view-valley-activity-diagram
skinparam ConditionEndStyle hline
|Игрок|
start
:Удаление аттракциона;
|Симуляция парка развлечений|
if (На "Главной аллее" есть посетители?) then (нет)
if (На аттракционе есть посетители?) then (нет) 
:Список аттракционов]
|Игрок|
:Выбор аттракциона;
:Подтвердить действие;
|Симуляция парка развлечений|
:Удалить аттракцион  из списка;
else (да)
:Действие невозможно]
endif
else (да)
:Действие невозможно]
|Игрок|
endif
stop
@enduml