@startuml
|Player|
start
:Remove the visitor from the park;
:Select a visitor from the list;
:Confirm action;
|Simulation of Entertainment Park|
:Remove the visitor from the list;
:Message about deletion]
:Visitor List]
|Player|
:View changes;
stop
@enduml