@startuml
|Player|
start
:Select the action;
if (Action) then (work with visitors)
:Working with visitors;
stop
else (work with the amusement park)
:Working with an amusement park;
stop
|Simulation of Entertainment Park|
@enduml