@startuml
|Player|
start
fork
:View "Main Valley";
forkagain
:View the attraction;
forkagain
:Removal of the attraction;
forkagain
repeat
:Buying an attraction;
|Simulation of Entertainment Park|
repeat while (amount of the attractions equals 10?) is (no) not (yes)
:Completion of the program]
stop
|Player|
endfork
stop
@enduml