@startuml
|Player|
start
If (Work with visitors is performed from the "Main Valley?") then (no)
repeat
fork
:Add a visitor;
forkagain
:Delete visitor;
endfork
repeat while (Buy a ticket?) is (no) not (yes)
:Purchase tickets;
stop
else (yes)
fork
:Move the visitor to the attraction;
forkagain
:Remove the visitor from the park;
endfork
stop
|Simulation of Entertainment Park|
@enduml