@startuml remove-visitor-from-park-activity-diagram
skinparam ConditionEndStyle hline
|Игрок|
start
|Симуляция парка развлечений|
:Список посетителей на "Главной аллее"]
|Игрок|
:Выбрать посетителей;
:Подтвердить действие;
|Симуляция парка развлечений|
:Добавить выбранных посетителей в очередь за билетами;
:Удалить посетителей из "Главной аллеи";
|Игрок|
stop
@enduml