@startuml remove-visitor-from-park-activity-diagram
skinparam ConditionEndStyle hline
|Player|
start
:Remove the visitor from the park;
|Simulation of Entertainment Park|
:List of visitors on the "Main Valley"]
|Player|
:Choose visitors;
:Confirm action;
|Simulation of Entertainment Park|
:Add selected visitors to the queue for tickets;
:Remove visitors from "Main Valley";
|Player|
stop
@enduml