@startuml turn-attraction-on-activity-diagram
skinparam ConditionEndStyle hline
|Player|
start
:Start the ride;
|Simulation of Entertainment Park|
if (Number of visitors in the queue > 1?) then (no)
:No action possible]
else (yes)
repeat
:Remove the first 10 visitors from the queue for the attraction;
:Add visitors to the riding list;
:Refresh seat count;
:Refresh time counter;
repeat while (Number of visitors in the queue is <= 10?) is (yes)
endif
stop
@enduml