@startuml turn-attraction-on-activity-diagram
skinparam ConditionEndStyle hline
|Игрок|
start
:Запуск аттракциона;
|Симуляция парка развлечений|
if (Количество посетителей в очереди > 1?) then (нет)
:Действие невозможно]
else (да)
repeat
:Удалить первых 10 посетителей из очереди на аттракцион;
:Добавить посетителей в список катающихся;
:Обновить счетчик занятых мест;
:Обновить счетчик времени;
repeat while (Количество посетителей в очереди <= 10?) is (да)
endif
stop
@enduml