@startuml view-attraction-activity-diagram
skinparam ConditionEndStyle hline
|Player|
start
:View the attraction;
|Simulation of Entertainment Park|
:List of attractions]
|Player|
:Choose an attraction;
fork
:Start the attraction;
|Simulation of Entertainment Park|
stop
forkagain
:List of visitors in queue]
forkagain
:Title of attraction]
forkagain
:Session time]
forkagain
:Seats on the attraction]
endfork
|Player|
stop
@enduml