@startuml view-valley-activity-diagram
skinparam ConditionEndStyle hline
|Player|
start
:View "Main Valley";
|Simulation of Entertainment Park|
:List of visitors on the "Main Valley"]
|Player|
:Working with visitors;
stop
@enduml