@startuml
|Игрок|
start
:Добавить посетителя;
|Симуляция парка развлечений|
:Сгенерировать ID;
:ID]
|Игрок|
repeat
:Ввести количество денежных средств;
:Подтвердить действие;
|Симуляция парка развлечений|
repeat while (Введено число от 1 до 100?) is (нет) not (да)
:Сохранить изменения;
:Список людей в очереди]
|Игрок|
:Просмотр изменений;
stop
@enduml