@startuml
|Игрок|
start
:Удалить посетителя из парка;
:Выбрать посетителя из списка;
:Подтвердить действие;
|Симуляция парка развлечений|
:Удалить посетителя из списка;
:Cообщение об удалении]
:Cписок посетителей]
|Игрок|
:Просмотр изменений;
stop
@enduml