@startuml
|Игрок|
start
if (Работа с посетителями ведется из "Главной аллеи?") then (нет)
repeat
fork
:Добавить посетителя;
forkagain
:Удалить посетителя;
endfork
repeat while (Купить билет?) is (нет) not (да)
:Приобрести билеты;
stop
else (да)
fork
:Определить посетителя на аттракцион;
forkagain
:Удалить посетителя из парка;
endfork
stop
@enduml