@startuml view-valley-activity-diagram
skinparam ConditionEndStyle hline
|Игрок|
start
:Просмотр "Главной аллеи";
|Симуляция парка развлечений|
:Список посетителей на "Главной аллее"]
|Игрок|
:Работа с посетителями;
stop
@enduml