@startuml
hide empty description

[*] --> Запуск_программы
    Запуск_программы : entry / <<main>> :: старт
    Запуск_программы --> Аттракционы : Окно_выбора_объекта:управление_аттракционами()
        Аттракционы : entry / Работа_с_аттракционами : просмотр_списка_аттракционов(list)
        Аттракционы : entry / Работа_с_аттракционами : купить_аттракцион()
        Аттракционы : entry / Работа_с_аттракционами : удалить_аттракцион()
        Аттракционы : entry / Работа_с_аттракционами : просмотр_аттракциона()
        Аттракционы : entry / Работа_с_аттракционами : просмотр_главной_аллеи()
        Аттракционы : exit / Работа_с_аттракционами : просмотр_списка_аттракционов(list) : Выйти

            Аттракционы --> Купить_аттракцион : Окно_работы_с_аттракционами:приобрести_аттракцион()
                Купить_аттракцион : entry / Управление_продажами_аттракционов : приобрести_аттракцион()
            Купить_аттракцион --> Аттракционы
            Аттракционы --> Удалить_аттракцион : Окно_работы_с_аттракционами:удаление_аттракциона()
                Удалить_аттракцион : entry / Управление_аттракционами : удаление_аттракциона()
            Удалить_аттракцион  --> Аттракционы    
            Аттракционы --> Просмотр_аттракциона : Окно_работы_с_аттракционами:просмотр_аттракциона()
                Просмотр_аттракциона : entry / Управление_аттракционами : просмотр_аттракциона()
                Просмотр_аттракциона : exit / Управление_аттракционами : просмотр_аттракциона() : Выйти
            Просмотр_аттракциона --> Аттракционы
            Аттракционы --> Просмотр_главной_аллеи : Окно_работы_с_главной_аллеей:просмотр_главной_аллеи()
                Просмотр_главной_аллеи : entry / Управление_главной_аллеей : приобрести_аттракцион()
                Просмотр_главной_аллеи : entry / Управление_главной_аллеей : удалить_аттракцион()
                Просмотр_главной_аллеи : entry / Управление_главной_аллеей : просмотр_посетителей()
                Просмотр_главной_аллеи : entry / Управление_главной_аллеей : вернуться_к_выбору_объекта()
            Просмотр_главной_аллеи --> Аттракционы


            Купить_аттракцион --> Завершить_программу
            Завершить_программу : exit <<main>>
            Завершить_программу --> [*]

            
       
@enduml