@startuml
hide empty description

[*] --> Start_Program
    Start_Program : entry / <<main>> :: start

    Start_Program --> Visitors : Window_object_selection:manage_visitors()
        Visitors : entry / work_with_visitors : add_visitor()
        Visitors : entry / work_with_visitors : delete_visitor()
        Visitors : entry / work_with_visitors : buy_ticket()
        Visitors : entry / work_with_visitors : define_visitor_to_attraction()
        Visitors : entry / work_with_visitors : delete_visitor_from_park()
        Visitors : entry / work_with_visitors : view_list_visitors()
        Visitors : exit / work_with_visitors : view_list_visitors() : Exit
            Visitors --> Add_Visitor: Work_With_Visitor_Window:Add_Visitor()
                Add_Visitor : entry / visitor : generate_ID();
                Add_Visitor : entry / visitor : add_payment(int);
                Add_Visitor : entry / visitor : save();
            Add_Visitor --> Visitors

            Visitors --> Delete_Visitor: Window_Work_with_visitors:Delete_visitor()
                Delete_Visitor : entry / controller : delete_visitor();
            Delete_Visitor --> Visitors

                    Delete_Visitor --> Purchase_Ticket: Window_Work_with_Visitors:Purchase_Ticket()
                    Add_Visitor --> Purchase_Ticket: Work_Window_with_visitors:Purchase_ticket()
                        Purchase_Ticket : entry / Sales_Management : purchase_ticket();
            
            Visitors --> Move_Visitor_To_Attraction: Work_Window_with_visitors:Purchase_Ticket()
                Move_Visitor_To_Attraction : entry / control_main_alley : move_visitor();
            Move_Visitor_To_Attraction --> Visitors
            
            Visitors --> Delete_Visitor_From_Park: Work_Window_with_visitors:Delete_Visitor_From_Park()
                Delete_Visitor_From_Park : entry / management of the main_alley : delete_visitor_from_park();
            Delete_Visitor_From_Park --> Visitors 
          
@enduml