@startuml
hide empty description

[*] --> Start_Program
    Start_Program : entry / <<main>> :: start
    Start_Program --> Attractions : Window_object_selection:Attraction_Control()
        Attractions : entry / work_with_attractions : view_list_attractions(list)
        Attractions : entry / work_with_attractions : buy_attraction()
        Attractions : entry / work_with_attractions : delete_attraction()
        Attractions : entry / work_with_attractions : view_attraction()
        Attractions : entry / work_with_attractions : view_main_valley()
        Attractions : exit / work_with_attractions : view_list_attractions(list) : exit

            Attractions --> Buy_Attraction : Window_work_with_attractions:Buy_Attraction()
                Buy_Attraction : enter / manage_sales_attractions : buy_attraction()
            Buy_Attraction --> Attractions
            Attractions --> Delete_Attraction : Window_work_with_attractions:Delete_Attraction()
                Delete_Attraction : enter / control_attraction : delete_attraction()
            Delete_Attraction --> Attractions    
            Attractions --> View_Attraction : Window_work_with_attractions:View_Attraction()
                View_Attraction : input / control_attraction : view_attraction()
                View_Attraction : exit / control_attraction : view_attraction() : exit
            View_Attraction --> Attractions
            Attractions --> View_Main_Valley : Window_work_with_main_valley:View_Main_Valley()
                View_Main_Valley : entry / control_main_alley : purchase_attraction()
                View_Main_Valley : enter / control_main_alley : delete_attraction()
                View_Main_Valley : entry / control_main_alley : view_visitors()
                View_Main_Valley : entry / control_main_alley : return_to_selection_object()
            View_Main_Valley --> Attractions


            Buy_Attraction --> Complete_Program
            Complete_Program : exit <<main>>
            Complete_Program --> [*]

            
       
@enduml