@startuml
Симуляция .[#MediumOrchid].> Инжектор_для_сувенирной_лавки: <<create>>
Симуляция_парка_развлечений <|-up- Инжектор_для_сувенирной_лавки
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Окно_сувенирной_лавки: <<create>>
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Сувенирная_Лавка: <<create>>
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Сувенир: <<create>>
Сувенир "1..*" <-[#MediumOrchid]down- "1" Сувенирная_Лавка: товар
Команда_Симуляции <|-[#MediumOrchid]down- Показать_сувенирную_лавку
Окно_работы_с_главной_аллеей "1\n +список_команд_симуляции" -down-> "1.." Команда_Симуляции
Показать_сувенирную_лавку "1" -[#MediumOrchid]-> " +окно_сувенирной_лавки" Окно_сувенирной_лавки
Посетитель <.[#MediumOrchid]. Сувенирная_Лавка: <<use>>
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Показать_сувенирную_лавку: <<create>>

class Симуляция << (M,Maroon) Main >> {
+ старт: void
}

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
}

class Инжектор_для_сувенирной_лавки << (I,Indigo) Injector >> #D0AAF3 {
+ создать_управление_сувенирной_лавкой(): void
}

class Окно_сувенирной_лавки << (U,DarkMagenta) UI>> {
    + просмотр_списка_цен_сувениров(): void
    + приобрести_сувенир(): void
    + просмотр_списка_сувениров_в_лавке(): void
    + просмотр_списка_сувениров_у_посетителя(): void

}


class Посетитель << (D,OrangeRed) Data>> {
}

class Сувенир << (D,OrangeRed) Data>> #D0AAF3 {
    + название: String
    + цена: int
}

class Сувенирная_Лавка #D0AAF3 {
    + приобрести_сувенир(int,int): void
    + список_сувениров_в_лавке(Сувенир): list
    + список_цен_сувениров(): list
    + список_сувениров_у_посетителя(Посетитель): list
}

class Окно_работы_с_главной_аллеей << (U,DarkMagenta) UI>> {
}

class Показать_сувенирную_лавку #D0AAF3 {
+ выполнить(selected): void
}
hide Показать_сувенирную_лавку circle

class Окно_сувенирной_лавки #D0AAF3 {
}

class Команда_Симуляции {
}
hide Команда_Симуляции circle

@enduml