@startuml
Симуляция .[#MediumOrchid].> Инжектор_для_контроля_рейтинга: <<create>>
Симуляция_парка_развлечений <|- Инжектор_для_контроля_рейтинга
Симуляция_парка_развлечений ..> Окно_выбора_объекта: <<create>>
Окно_выбора_объекта  "1" --> " +окно_просмотра_аттракциона\n1" Окно_просмотра_аттракциона
Инжектор_для_контроля_рейтинга .[#MediumOrchid].> Управление_отзывамиImpl: <<create>>
Окно_просмотра_аттракциона_с_рейтингом "1" o-[#MediumOrchid]- " +создать\n1" Управление_отзывамиImpl
Окно_просмотра_аттракциона <|- Окно_просмотра_аттракциона_с_рейтингом
Инжектор_для_контроля_рейтинга .[#MediumOrchid].> Рейтинг_Аттракциона: <<create>>
Симуляция_парка_развлечений ..> Аттракцион: <<create>>
Рейтинг_Аттракциона "1" <-[#MediumOrchid]- "1..*" Аттракцион: рейтинг

class Симуляция << (M,Maroon) Main >> {
+ старт: void
}

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
}

class Инжектор_для_контроля_рейтинга << (I,Indigo) Injector >> #D0AAF3 {
+ создать_управление_отзывами(): void
}

class Управление_отзывамиImpl << (I,MidnightBlue) >> {
    + добавить_оценку(int): int
    + просмотр_рейтинга(): list
    + показать_список_оценок_аттракционов(): list
}

class Окно_просмотра_аттракциона << (U,DarkMagenta) UI>> {

}

class Окно_просмотра_аттракциона_с_рейтингом << (U,DarkMagenta) UI>> #A155E7 {
    + добавить_оценку(): void
    + просмотр_рейтинга(): void
}

class Рейтинг_Аттракциона #A155E7 {
    + оценка_аттракциона(int)
    + поставить_оценку(int): void
    + список_оценок_аттракционов(): list
}

class Аттракцион {
}

class Окно_выбора_объекта << (U,DarkMagenta) UI>> {
}

class Управление_отзывамиImpl #A155E7 {
}

@enduml