@startuml
Симуляция .[#MediumOrchid].> Инжектор_для_сувенирной_лавки: <<create>>
Симуляция_парка_развлечений <|-up- Инжектор_для_сувенирной_лавки
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Управление_сувенирной_лавкойImpl: <<create>>
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Окно_сувенирной_лавки: <<create>>
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Сувенирная_Лавка: <<create>>
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Сувенир: <<create>>
Сувенир "1..*" <-[#MediumOrchid]down- "1" Сувенирная_Лавка: товар
Окно_работы_с_главной_аллеей <|-down- Окно_работы_с_сувенирной_лавкой_на_главной_аллее
Окно_работы_с_сувенирной_лавкой_на_главной_аллее "1" -[#MediumOrchid]-> " +окно_сувенирной_лавки" Окно_сувенирной_лавки
Управление_сувенирной_лавкойImpl " +окно_сувенирной_лавки\n 1" -[#MediumOrchid]-o "1" Окно_сувенирной_лавки
Управление_сувенирной_лавкойImpl " +создать\n 1" -[#MediumOrchid]-o "1" Окно_работы_с_сувенирной_лавкой_на_главной_аллее
Посетитель "1..*" <-[#MediumOrchid] "1" Сувенирная_Лавка: клиент
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Окно_работы_с_посетителями_в_сувенирной_лавке: <<create>>
Инжектор_для_сувенирной_лавки .[#MediumOrchid].> Окно_работы_с_сувенирной_лавкой_на_главной_аллее: <<create>>
Окно_работы_с_посетителями <|-down- Окно_работы_с_посетителями_в_сувенирной_лавке

class Симуляция << (M,Maroon) Main >> {
+ старт: void
}

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
}

class Инжектор_для_сувенирной_лавки << (I,Indigo) Injector >> #D0AAF3 {
+ создать_управление_сувенирной_лавкой(): void
}

class Окно_сувенирной_лавки << (U,DarkMagenta) UI>> {
    + просмотр_списка_цен_сувениров(): void
    + приобрести_сувенир(): void
    + просмотр_списка_сувениров_в_лавке(): void
}

class Управление_сувенирной_лавкойImpl << (I,MidnightBlue) >> {
    + просмотр_списка_цен_сувениров(): list
    + приобрести_сувенир(int,int): void
    + просмотр_списка_сувениров_в_лавке(): list
    + просмотр_списка_сувениров_у_посетителя(): list
}

class Окно_работы_с_посетителями << (U,DarkMagenta) UI>> {
}

class Окно_работы_с_посетителями_в_сувенирной_лавке << (U,DarkMagenta) UI>> #A155E7{
    + просмотр_списка_сувениров_у_посетителя(): void
    + приобрести_билет(): void
}

class Посетитель << (D,OrangeRed) Data>> {
}

class Сувенир << (D,OrangeRed) Data>> #A155E7 {
    + название: String
    + цена: int
}

class Сувенирная_Лавка #A155E7 {
    + приобрести_сувенир(int,int): void
    + список_сувениров_в_лавке(): list
    + список_цен_сувениров(): list
}

class Окно_работы_с_главной_аллеей << (U,DarkMagenta) UI>> {
}

class Окно_работы_с_сувенирной_лавкой_на_главной_аллее << (U,DarkMagenta) UI>> #A155E7 {
    + приобрести_сувенир(): void
}

class Окно_сувенирной_лавки #A155E7 {
}

class Управление_сувенирной_лавкойImpl #A155E7 {
}
@enduml