@startuml
Симуляция_парка_развлечений .left.> Управление_сувенирной_лавкойImpl: <<create>>
Симуляция_парка_развлечений ..> Окно_сувенирной_лавки: <<create>>
Симуляция_парка_развлечений ..> Окно_работы_с_посетителями: <<create>>
Симуляция_парка_развлечений ..> Посетитель: <<create>>
Симуляция_парка_развлечений .> Сувенирная_Лавка: <<create>>
Окно_работы_с_главной_аллеей "1" --> " +окно_сувенирной_лавки" Окно_сувенирной_лавки
Управление_сувенирной_лавкойImpl " +окно_сувенирной_лавки\n 1" --o "1" Окно_сувенирной_лавки
Управление_сувенирной_лавкойImpl " +создать\n 1" --o "1" Окно_работы_с_главной_аллеей
Посетитель "1..*" <-- "1" Сувенирная_Лавка: клиент

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
+ создать_управление_сувенирной_лавкой(): void
}

class Окно_сувенирной_лавки << (U,DarkMagenta) UI>> {
    + просмотр_списка_цен_сувениров(): void
    + приобрести_сувенир(): void
    + просмотр_списка_сувениров_в_лавке(): void
}

class Управление_сувенирной_лавкойImpl << (I,MidnightBlue) >> {
    + просмотр_списка_цен_сувениров(): list
    + приобрести_сувенир(int,int): void
    + просмотр_списка_сувениров_в_лавке(): list
    + просмотр_списка_сувениров_у_посетителя(): list
}

class Окно_работы_с_посетителями << (U,DarkMagenta) UI>> {
    + просмотр_списка_сувениров_у_посетителя(): void
    + приобрести_билет(): void
}

class Посетитель {
    + зарплата: int
    + id: int
    + список_сувениров_у_посетителя(): list
}

class Сувенирная_Лавка << (C,#a4e8e0) >> {
    + приобрести_сувенир(int,int): void
    + список_сувениров_в_лавке(): list
    + список_цен_сувениров(): list
}

class Окно_работы_с_главной_аллеей << (U,DarkMagenta) UI>> {
    + приобрести_сувенир(): void
}
@enduml