@startuml
Симуляция_парка_развлечений ..> Окно_выбора_объекта: <<create>>
Окно_выбора_объекта  "1" --> " +окно_просмотра_аттракциона\n1" Окно_просмотра_аттракциона
Симуляция_парка_развлечений .[#red].> Управление_отзывамиImpl: <<create>>
Окно_просмотра_аттракциона "1" o-[#red]- " +создать\n1" Управление_отзывамиImpl
Симуляция_парка_развлечений .[#red].> Рейтинг_Аттракциона: <<create>>
Симуляция_парка_развлечений ..> Аттракцион: <<create>>
Рейтинг_Аттракциона "1" <-[#red]- "1..*" Аттракцион: рейтинг

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
+ создать_управление_отзывами(): void
}

class Управление_отзывамиImpl << (I,MidnightBlue) >> {
    + добавить_оценку(int): int
    + просмотр_рейтинга(): list
    + показать_список_оценок_аттракционов(): list
}

class Окно_просмотра_аттракциона << (U,DarkMagenta) UI>> {
    + добавить_оценку(): void
    + просмотр_рейтинга(): void
}

class Рейтинг_Аттракциона #ff9999 {
    + оценка_аттракциона(int)
    + поставить_оценку(int): void
    + список_оценок_аттракционов(): list
}

class Аттракцион {
}

class Окно_выбора_объекта << (U,DarkMagenta) UI>> {
}

class Управление_отзывамиImpl #ff9999 {
}

@enduml