@startuml
Симуляция ..> Инжектор_с_мелодией: <<create>>
Инжектор_с_мелодией .[#MediumOrchid].> Мелодия: <<use>>
Симуляция_парка_развлечений <|- Инжектор_с_мелодией
Показать_окно_выбора_объекта <|-[#MediumOrchid]- Показать_окно_выбора_объекта_с_мелодией
Команда_Симуляции <|-[#MediumOrchid]- Команда_Симуляции_с_Мелодией
Показать_окно_выбора_объекта_с_мелодией .[#MediumOrchid].> Мелодия: <<use>>
Команда_Симуляции_с_Мелодией .[#MediumOrchid].> Мелодия: <<use>>

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
}

class Инжектор_с_мелодией << (I,Indigo) Injector >> #D0AAF3 {
+ воспроизвести_мелодию(): мелодия
}

class Показать_окно_выбора_объекта {
}

class Показать_окно_выбора_объекта_с_мелодией #A155E7 {
    + выполнить(): void
    + воспроизвести_мелодию(): мелодия
}

class Симуляция << (M,Maroon) Main >> {
+ старт: void
}

class Команда_Симуляции {
}

class Команда_Симуляции_с_Мелодией #A155E7 {
    + воспроизвести_мелодию(): мелодия
}

class Мелодия << (D,OrangeRed) Data>> #A155E7 {
    + мелодия
}

hide Показать_окно_выбора_объекта circle
hide Команда_Симуляции circle

Симуляция_парка_развлечений ..> Показать_окно_выбора_объекта: <<create>>
Показать_окно_выбора_объекта -|> Команда_Симуляции
Команда_Симуляции_с_Мелодией " +команды\n 1..*" -[#MediumOrchid]-o "1" Окно_Симуляции_парка_развлечений
@enduml