@startuml
Симуляция .[#MediumOrchid].> Инжектор_для_контроля_рейтинга: <<create>>
Симуляция_парка_развлечений <|- Инжектор_для_контроля_рейтинга
Инжектор_для_контроля_рейтинга .[#MediumOrchid].> Рейтинг_Аттракциона: <<create>>
Рейтинг_Аттракциона .[#MediumOrchid].>  Аттракцион: <<use>>
Команда_Симуляции <|-up- Добавить_оценку
Команда_Симуляции <|-up- Просмотр_рейтинга
Инжектор_для_контроля_рейтинга .[#MediumOrchid].> Добавить_оценку: <<create>>
Инжектор_для_контроля_рейтинга .[#MediumOrchid].> Просмотр_рейтинга: <<create>>
Инжектор_для_контроля_рейтинга .[#MediumOrchid].> Контроллер_просмотра_рейтинга_аттракциона: <<create>>
Контроллер <|- Контроллер_просмотра_рейтинга_аттракциона
Контроллер_просмотра_рейтинга_аттракциона "1 \n+контроллер" <-[#MediumOrchid]- "1" Добавить_оценку
Контроллер_просмотра_рейтинга_аттракциона "1" <-[#MediumOrchid]- "1\n+контроллер" Просмотр_рейтинга
Контроллер_просмотра_рейтинга_аттракциона "1" -[#MediumOrchid]up-> "1..\n+рейтинг_аттракционов" Рейтинг_Аттракциона

class Симуляция << (M,Maroon) Main >> {
+ старт: void
}

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
}

class Инжектор_для_контроля_рейтинга << (I,Indigo) Injector >> #D0AAF3 {
+ создать_управление_отзывами(): void
}


class Добавить_оценку #D0AAF3 {
    + выполнить(selected): void

}
hide Добавить_оценку circle

class Просмотр_рейтинга #D0AAF3 {
    + выполнить(selected): void
}
hide Просмотр_рейтинга circle


class Контроллер_просмотра_рейтинга_аттракциона #D0AAF3 {
    + override создать_аттракцион(): void
    + добавить_оценку(): void
    + просмотр_рейтинга(): void
}

class Команда_Симуляции {
    - название: string
    + выполнить(selected): void
}
hide Команда_Симуляции circle

class Рейтинг_Аттракциона #D0AAF3 {
    + оценка_аттракциона(Aттракцион)
    + поставить_оценку(int): void
    + список_оценок_аттракционов(): list
}

class Контроллер << (C,#a4e8e0) >> {
}

@enduml