@startuml
Симуляция ..> Инжектор_с_мелодией: <<create>>
Инжектор_с_мелодией .[#MediumOrchid].> Мелодия: <<create>>
Инжектор_с_мелодией .[#MediumOrchid].> Команда_Симуляции_с_Мелодией: <<create>>
Инжектор_с_мелодией .[#MediumOrchid].> Показать_окно_выбора_объекта_с_мелодией: <<create>>
Симуляция_парка_развлечений <|- Инжектор_с_мелодией
Показать_окно_выбора_объекта <|-[#MediumOrchid]- Показать_окно_выбора_объекта_с_мелодией
Команда_Симуляции <|-[#MediumOrchid]- Команда_Симуляции_с_Мелодией
Показать_окно_выбора_объекта_с_мелодией .[#MediumOrchid].> Мелодия: <<use>>
Команда_Симуляции_с_Мелодией .[#MediumOrchid].> Мелодия: <<use>>

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
}

class Инжектор_с_мелодией << (I,Indigo) Injector >> #D0AAF3 {
}

class Показать_окно_выбора_объекта {
}

class Показать_окно_выбора_объекта_с_мелодией #D0AAF3 {
    + выполнить(): void
    + воспроизвести_мелодию(мелодия): void
}

class Симуляция << (M,Maroon) Main >> {
+ старт: void
}

class Команда_Симуляции {
}

class Команда_Симуляции_с_Мелодией #D0AAF3 {
    + воспроизвести_мелодию(мелодия): void
}

class Мелодия << (D,OrangeRed) Data>> #D0AAF3 {
    + мелодия
    + выполнить()
}

hide Показать_окно_выбора_объекта circle
hide Команда_Симуляции circle

Симуляция_парка_развлечений ..> Показать_окно_выбора_объекта: <<create>>
Показать_окно_выбора_объекта -|> Команда_Симуляции
@enduml