@startuml
Симуляция ..> Симуляция_парка_развлечений: <<create>>
Симуляция_парка_развлечений .[#red].> Мелодия: <<create>>

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
+ воспроизвести_мелодию(): Music
}

class Показать_окно_выбора_объекта {
    - название: string
    + выполнить(): void
    + воспроизвести_мелодию(): Music
}

class Симуляция << (M,Maroon) Main >> {
+ старт: void
}

class Окно_старта << (U,DarkMagenta) UI>> {
    + старт(): void
}

class Команда_Симуляции {
    + выполнить(): void
    + воспроизвести_мелодию(): Music
}

class Окно_Симуляции_парка_развлечений << (U,DarkMagenta) UI>> {
    + нажатаКнопка(string): void
}

class Мелодия #ff9999 {
    + воспроизвести_мелодию(): Music
    + мелодия
}

hide Показать_окно_выбора_объекта circle
hide Команда_Симуляции circle

Симуляция_парка_развлечений ..> Показать_окно_выбора_объекта: <<create>>
Показать_окно_выбора_объекта -[#red]-|> Команда_Симуляции
Команда_Симуляции " +команды\n 1..*" --o "1" Окно_Симуляции_парка_развлечений
Окно_старта "1" -up->" 1\n+оконо_симуляции_парка_развлечений" Окно_Симуляции_парка_развлечений
@enduml