@startuml add-visitor-to-attraction-activity-diagram
skinparam ConditionEndStyle hline
|Игрок|
start
:Определить посетителя на аттракцион;
|Симуляция парка развлечений|
fork
:Список посетителей на "Главной аллее"]
forkagain
:Список аттракционов]
endfork
|Игрок|
fork
:Выбрать посетителей;
forkagain
:Выбрать аттракцион;
endfork
:Подтвердить действие;
|Симуляция парка развлечений|
:Добавить выбранных посетителей в очередь на аттракцион;
:Удалить посетителей из "Главной аллеи";
|Игрок|
stop
@enduml