@startuml
skinparam ConditionEndStyle hline
|Игрок|
start
:Покупка аттракциона;
|Симуляция парка развлечений|
if (На "Главной аллее" есть посетители?) then (нет)
if (На аттракционе есть посетители?) then (нет)
:Вычислить стоимость аттракциона;
:Стоимость аттракциона] 
|Игрок|
:Подтвердить действие;
|Симуляция парка развлечений|
if (В бюджете парка достаточно средств?) then (да)
:Обновить значение бюджета парка;
|Игрок|
repeat
:Ввести название;
:Подтвердить действие;
|Симуляция парка развлечений|
repeat while (Данные корректны?) is (нет) not (да)
:Название аттракциона]
:Добавить аттракцион в список;
else (нет)
:Действие невозможно]
endif
else (да)
:Действие невозможно]
endif
else (да)
:Действие невозможно]
|Игрок|
endif
stop
@enduml