@startuml buy-ticket
skinparam ConditionEndStyle hline
|Игрок|
start
:Приобрести билет;
:Подтвердить действие;
|Симуляция парка развлечений|
:Вычислить стоимость билета;
:Cтоимость билета]
|Игрок|
:Выбрать посетителя;
:Подтвердить действие;
|Симуляция парка развлечений|
if (У посетителя хватает средств на покупку?) then (да)
:Записать остаток средств посетителя;
:Пополнить бюджет парка;
:Посетитель перемещен на "Главную Аллею"]
else (нет)
|Симуляция парка развлечений|
:Удалить посетителя из списка;
endif
|Игрок|
stop
@enduml