@startuml
|Игрок|
start
fork
:Просмотр "Главной аллеи";
forkagain
:Просмотр аттракциона;
forkagain
:Удаление аттракциона;
forkagain
repeat
:Покупка аттракциона;
|Симуляция парка развлечений|
repeat while (Аттракционов 10?) is (нет) not (да)
:Завершение программы]
stop
|Игрок|
endfork
stop
@enduml