@startuml view-attraction-activity-diagram
skinparam ConditionEndStyle hline
|Игрок|
start
:Просмотр аттракциона;
|Симуляция парка развлечений|
:Список аттракционов]
|Игрок|
:Выбрать аттракцион;
fork
:Запустить аттракцион;
|Симуляция парка развлечений|
stop
forkagain
:Список посетителей в очереди]
forkagain
:Название аттракциона]
forkagain
:Время сеанса]
forkagain
:Места на аттракционе]
endfork
|Игрок|
stop
@enduml