@startuml
hide empty description

[*] --> Запуск_программы
    Запуск_программы : entry / <<main>> :: старт

    Запуск_программы --> Посетители : Окно_выбора_объекта:управление_посетителями()
        Посетители : entry / Работа_с_посетителями : добавить_посетителя()
        Посетители : entry / Работа_с_посетителями : удалить_посетителя()
        Посетители : entry / Работа_с_посетителями : приобрести_билет()
        Посетители : entry / Работа_с_посетителями : определить_посетителя_на_аттракцион()
        Посетители : entry / Работа_с_посетителями : удалить_посетителя_из_парка()
        Посетители : entry / Работа_с_посетителями : просмотр_списка_поетителей()
        Посетители : exit / Работа_с_посетителями : просмотр_списка_поетителей() : Выйти
            Посетители --> Добавить_посетителя: Окно_работы_с_посетителями:добавить_посетителя()
                Добавить_посетителя : entry / Посетитель : сгенерировать_ID();
                Добавить_посетителя : entry / Посетитель : добавить_зарплату(int);
                Добавить_посетителя : entry / Посетитель : сохранить();
            Добавить_посетителя --> Посетители

            Посетители --> Удалить_посетителя: Окно_работы_с_посетителями:удалить_посетителя()
                Удалить_посетителя : entry / Контроллер : удалить_посетиетля();
            Удалить_посетителя --> Посетители

                    Удалить_посетителя --> Приобрести_билет: Окно_работы_с_посетителями:приобрести_билет()
                    Добавить_посетителя --> Приобрести_билет: Окно_работы_с_посетителями:приобрести_билет()
                        Приобрести_билет : entry / Управление_продажами_билетов : приобрести_билет();
            
            Посетители --> Определить_посетителя_на_аттракцион: Окно_работы_с_посетителями:приобрести_билет()
                Определить_посетителя_на_аттракцион : entry / Управление_главной_аллеей : переместить_посетителя();
            Определить_посетителя_на_аттракцион --> Посетители
            
            Посетители --> Удалить_посетителя_из_парка: Окно_работы_с_посетителями:удалить_посетителя_из_парка()
                Удалить_посетителя_из_парка : entry / Управление_главной_аллеей : удалить_посетителя_из_парка();
            Удалить_посетителя_из_парка --> Посетители 
     
@enduml