@startuml
class Окно_работы_с_посетителями << (U,DarkMagenta) UI>> {
}

class Окно_работы_с_аттракционами << (U,DarkMagenta) UI>> {
}

class Окно_работы_с_главной_аллеей << (U,DarkMagenta) UI>> {
}

class Окно_просмотра_аттракциона << (U,DarkMagenta) UI>> {
}

class Команда_Симуляции {
}
hide Команда_Симуляции circle

Команда_Симуляции "+список_команд_симуляции \n 1.."<-up- "1"  Окно_работы_с_посетителями
Команда_Симуляции "1.."<-up- "1\n +список_команд_симуляции"  Окно_работы_с_аттракционами
Команда_Симуляции "1.."<-- "1\n +список_команд_симуляции" Окно_работы_с_главной_аллеей
Команда_Симуляции "1.."<-- "1\n +список_команд_симуляции" Окно_просмотра_аттракциона

@enduml