@startuml
Окно_выбора_объекта "1" o-up- " +cоздать\n 1" Управление_посетителямиImpl
Окно_выбора_объекта "1" o-up- " +cоздать\n 1" Управление_аттракционамиImpl
Окно_выбора_объекта "1" o-- " +cоздать\n 1" Управление_паркомImpl
Окно_работы_с_посетителями "1" o-- " +cоздать\n 1" Управление_посетителямиImpl
Окно_работы_с_посетителями "1" o-up- " +cоздать\n 1" Управление_продажами_билетовImpl
Окно_работы_с_аттракционами "1" o-- " +cоздать\n 1" Управление_аттракционамиImpl
Окно_работы_с_аттракционами "1" o-up- " +cоздать\n 1" Управление_продажами_аттракционовImpl
Окно_работы_с_главной_аллеей "1" o-- " +cоздать\n 1" Управление_Главной_АллеейImpl
Окно_работы_с_главной_аллеей "1" o-- " +cоздать\n 1" Управление_посетителямиImpl
Окно_работы_с_главной_аллеей "1" o-- " +cоздать\n 1" Управление_аттракционамиImpl


class Окно_выбора_объекта << (U,DarkMagenta) UI>> {
}

class Окно_работы_с_посетителями << (U,DarkMagenta) UI>> {
}

class Окно_работы_с_аттракционами << (U,DarkMagenta) UI>> {
}

class Окно_работы_с_главной_аллеей << (U,DarkMagenta) UI>> {
}

class Управление_посетителямиImpl << (I,MidnightBlue) >> {
}

class Управление_паркомImpl << (I,MidnightBlue) >> {
}

class Управление_аттракционамиImpl << (I,MidnightBlue) >> {
}

class Управление_Главной_АллеейImpl << (I,MidnightBlue) >> {
}

class Управление_продажами_билетовImpl << (I,MidnightBlue) >> {
}


class Управление_продажами_аттракционовImpl << (I,MidnightBlue) >> {
}
@enduml