@startuml
class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
}

class Окно_работы_с_посетителями << (U,DarkMagenta) UI>> {
}

class Окно_работы_с_аттракционами << (U,DarkMagenta) UI>> {
}

class Окно_работы_с_главной_аллеей << (U,DarkMagenta) UI>> {
}

class Окно_просмотра_аттракциона << (U,DarkMagenta) UI>> {
}

class Окно_Симуляции_парка_развлечений << (U,DarkMagenta) UI>> {
}

Симуляция_парка_развлечений .up.> Окно_работы_с_посетителями: <<create>>
Симуляция_парка_развлечений .up.> Окно_работы_с_аттракционами: <<create>>
Симуляция_парка_развлечений ..> Окно_работы_с_главной_аллеей: <<create>>
Симуляция_парка_развлечений ..> Окно_просмотра_аттракциона: <<create>>
Симуляция_парка_развлечений ..> Окно_Симуляции_парка_развлечений: <<create>>

@enduml