@startuml
Симуляция ..> Симуляция_парка_развлечений: <<create>>

class Симуляция << (M,Maroon) Main >> {
+ старт: void
}

class Симуляция_парка_развлечений << (I,Indigo) Injector >> {
+ инициализация(): void
+ создать_UI(): void
+ создать_управление_парком(): void
+ создать_управление_посетителями(): void
+ создать_управление_аттракционами(): void
+ создать_управление_продажами_билетов(): void
+ создать_управление_продажами_аттракционов(): void
+ создать_управление_главной_аллеей(): void
+ создать_Управление_использованием_аттракциона(): void
}

class Окно_старта << (U,DarkMagenta) UI>> {
    + старт(): void
}

class Окно_выбора_объекта << (U,DarkMagenta) UI>> {
    + управление_посетителями(): void
    + управление_аттракционами(): void
    + бюджет_парка(): void
}

class Окно_работы_с_посетителями << (U,DarkMagenta) UI>> {
    + просмотр_списка_посетителей(): void
    + добавить_посетителя(): void
    + приобрести_билет(): void
    + удалить_посетителя(): void

}

class Окно_работы_с_аттракционами << (U,DarkMagenta) UI>> {
    + просмотр_списка_аттракционов(): void
    + купить_аттракцион(): void
    + удалить_аттракцион(): void
    
}

class Окно_работы_с_главной_аллеей << (U,DarkMagenta) UI>> {
    + просмотр_списка_аттракционов(): void
    + просмотр_посетителей_на_аллее(): void
    + удалить_посетителя_из_парка(): void
    + переместить_посетителя(): void
    + вернуться_к_выбору_объекта(): void

}

class Окно_просмотра_аттракциона << (U,DarkMagenta) UI>> {
    + просмотр_очереди_посетителей(): void
    + просмотр_посетителей_на_аттракционе(): void
    + запуск_аттракциона(): void
    }

Симуляция_парка_развлечений ..> Окно_старта: <<create>>
Окно_старта "1" -->" +Окно_выбора_объекта" Окно_выбора_объекта
Окно_выбора_объекта "1" -up->" +окно_работы_с_посетителями" Окно_работы_с_посетителями
Окно_выбора_объекта "1" --up->" +окно_работы_с_аттракционами" Окно_работы_с_аттракционами
Окно_выбора_объекта "1" -->" +окно_работы_с_главной_аллеей" Окно_работы_с_главной_аллеей
Окно_выбора_объекта "1" -->" +окно_просмотра_аттракциона" Окно_просмотра_аттракциона

class Показать_окно_выбора_объекта << (U,DarkMagenta) UI>> {
    - название: string
    + выполнить(): void
}

class Команда_Симуляции {
    + выполнить(): void
}

hide Команда_Симуляции circle

Симуляция_парка_развлечений ..> Показать_окно_выбора_объекта: <<create>>
Показать_окно_выбора_объекта --|> Команда_Симуляции


@enduml