@startuml
Окно_просмотра_аттракциона "1" o-up- " +cоздать\n 1" Управление_использованием_аттракционаImpl

class Окно_просмотра_аттракциона << (U,DarkMagenta) UI>> {
}

class Управление_использованием_аттракционаImpl << (I,MidnightBlue) >> {
}
@enduml